---
# tasks file for common role
- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled

- name: Disable Swap
  block:
    - name: Turn off swap
      ansible.builtin.command: swapoff -a
    - name: Comment out swap in fstab
      ansible.builtin.replace:
        path: /etc/fstab
        regexp: '^(.*swap.*)$'
        replace: '# \1'
  when: ansible_swaptotal_mb > 0

- name: Configure kernel modules and sysctl for Kubernetes
  block:
    - name: Load overlay module
      community.general.modprobe: { name: overlay, state: present }
    - name: Load br_netfilter module
      community.general.modprobe: { name: br_netfilter, state: present }
    - name: Create k8s.conf for sysctl
      ansible.builtin.copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward                 = 1
    - name: Apply sysctl params
      ansible.builtin.command: sysctl --system

- name: Install and configure containerd
  block:
    - name: Install required packages for containerd
      ansible.builtin.dnf:
        name: [dnf-utils, device-mapper-persistent-data, lvm2]
        state: present
    - name: Add Docker CE repository
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
    - name: Install containerd.io
      ansible.builtin.dnf:
        name: containerd.io
        state: present
    - name: Configure containerd to use systemd cgroup
      ansible.builtin.shell: |
        mkdir -p /etc/containerd
        containerd config default > /etc/containerd/config.toml
        sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml
    - name: Restart and enable containerd service
      ansible.builtin.systemd:
        name: containerd
        state: restarted
        enabled: yes

- name: Add Kubernetes v1.32 yum repository
  ansible.builtin.yum_repository:
    name: kubernetes
    description: Kubernetes
    # --- 版本更新点 ---
    baseurl: https://pkgs.k8s.io/core:/stable:/v1.32/rpm/
    gpgkey: https://pkgs.k8s.io/core:/stable:/v1.32/rpm/repodata/repomd.xml.key
    gpgcheck: yes
    enabled: yes
    exclude: kubelet kubeadm kubectl cri-tools kubernetes-cni

- name: Install Kubernetes components
  ansible.builtin.dnf:
    name: [kubelet, kubeadm, kubectl]
    state: present
    disable_excludes: kubernetes

- name: Enable kubelet service
  ansible.builtin.systemd:
    name: kubelet
    enabled: yes
