apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argocd.argoproj.io
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated: { selfHeal: true } # 只开启自愈，不开启自动修剪
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: kube-prometheus-stack
    targetRevision: 57.2.0
    helm:
      # Argo CD会用这些values来比对，确保安装的状态一致
      values: |
        grafana:
          service:
            type: NodePort
        prometheus:
          service:
            type: NodePort
        alertmanager:
          service:
            type: NodePort
